version: '3'
services:
  api:
    container_name: api
    build:
      context: ./docker/python/
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    command:  uvicorn main:app --reload --host 0.0.0.0 --port 8000
  frontend:
    container_name: frontend
    build:
      context: ./docker/react/
    ports:
      - 3000:5173
    volumes:
      - ./frontend:/frontend
    command: npm run dev